version: "3.9"

services: 
  mysql: 
    container_name: mysql_database
    image: mysql:oracle
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=example
      - MYSQL_USER=carlos
      - MYSQL_PASSWORD=1234
    volumes:
      - "../databases/mysql:/var/lib/mysql"
    restart: "always"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  phpMyAdmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: "always"
    depends_on:
      mysql: 
        condition: service_healthy
    

networks:
  mysql:
    name: mysql
